### ISSUE TITLE
Expired mirror

### ISSUE THREAD

**Issue by r3tr0g4m3r** [AlmaLinux/mirrors#103]
Greetings, we have noticed that our mirror is listed as expired, however we are synced every 3 hours, what could be wrong?.

https://mirror.netglobalis.net/almalinux/

**Comment by andrewlukoshko** [comment]
Hello!
We use http://mirror.netglobalis.net/almalinux/TIME file to check if mirror expired.
Right now it shows that mirror is more than 10 hours old.
Maybe you use caching or something and we get outdated TIME file?

**Comment by r3tr0g4m3r** [comment]
Thanks for the reply Andrew, indeed the file was older, we have retouched our cron to run every 3 hours as recommended.

**Comment by andrewlukoshko** [comment]
Now your mirror listed as OK: https://mirrors.almalinux.org
Thanks. Closing.
