### ISSUE TITLE
legacy.repo.almalinux.org only on ipv4

### ISSUE THREAD

**Issue by Algirdas-Z** [AlmaLinux/mirrors#1047]
Hello,

Is there a reason for `legacy.repo.almalinux.org` repo to be ipv4 only? This creates some issues if hosts are ipv6 only.
Thank you.

**Comment by jonathanspw** [comment]
This is only a legacy update host for some CloudLinux servers.  After getting up to date you should then hit the main mirrorlist.

Are you running CloudLinux with only ipv6?

**Comment by Algirdas-Z** [comment]
Yep, fresh cloudlinux after kickstart is being updated only using ipv6.  
in short, actually ansible fails to run role, because it tries to install package and this mirror gives error (since there is no ipv6 AAAA record)   
\`\`\`  
Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Curl error (7): Couldn't connect to server for https://legacy.repo.almalinux.org:443/mirrorlist/8.9/appstream \[\]"  
\`\`\`

**Comment by jonathanspw** [comment]
I've added an IPv6 AAAA record.  Can you verify this solves your problem?

**Comment by Algirdas-Z** [comment]
```
 curl -6 https://legacy.repo.almalinux.org/mirrorlist/8.9/appstream
curl: (7) Failed to connect to legacy.repo.almalinux.org port 443: Connection refused
```

Maybe something else needs to be done, sometimes also I get "could not resolve" but thats expected while DNS is propagating, however 443 (refused) isn't dns problem :)

**Comment by jonathanspw** [comment]
> ```
>  curl -6 https://legacy.repo.almalinux.org/mirrorlist/8.9/appstream
> curl: (7) Failed to connect to legacy.repo.almalinux.org port 443: Connection refused
> ```
> 
> Maybe something else needs to be done, sometimes also I get "could not resolve" but thats expected while DNS is propagating, however 443 (refused) isn't dns problem :)

Had to update nginx to actually listen on v6.  Try now :)

**Comment by Algirdas-Z** [comment]
Yep, works fine now, appreciated! :)
