### ISSUE TITLE
My private mirror not being returned in mirrorlist

### ISSUE THREAD

**Issue by brianjmurrell** [AlmaLinux/mirrors#1103]
My private mirror as described by https://github.com/AlmaLinux/mirrors/blob/master/mirrors.d/pkgs.interlinx.bc.ca.yml is not being returned from https://mirrors.almalinux.org/mirrorlist/8.10/baseos.

I've now just made a query to https://mirrors.almalinux.org/mirrorlist/99.995/baseos to provide you a log entry with which you can see the source of my queries and why they would not be matching the above mirror entry.  As an aside, interestingly enough, the query for `99.995` returned mirror entries for `9.4`.  Is that expected?  I would have thought it would have returned some kind of _invalid version_ type of error.  But perhaps that's a new/different ticket.

**Comment by codyro** [comment]
>  As an aside, interestingly enough, the query for 99.995 returned mirror entries for 9.4. Is that expected?

Nope! That's definitely a bug.

It looks like the logic in the version matching is flawed (https://github.com/AlmaLinux/mirrors/blob/mirrors_service/src/backend/api/handlers.py#L416). 

```shell
codyr@Portia ~/D/G/mirrors (mirrors_service)> curl https://mirrors.almalinux.org/mirrorlist/99.345/baseos                                        2024-10-06 16:06:46
http://nyc.mirrors.clouvider.net/almalinux/9.4/BaseOS/$basearch/os/
http://ohioix.mm.fcix.net/almalinux/9.4/BaseOS/$basearch/os/
http://mirror.servaxnet.com/almalinux/9.4/BaseOS/$basearch/os/
http://mirror.clarkson.edu/almalinux/9.4/BaseOS/$basearch/os/
http://us.mirrors.cicku.me/almalinux/9.4/BaseOS/$basearch/os/
http://uvermont.mm.fcix.net/almalinux/9.4/BaseOS/$basearch/os/
http://mirror.siena.edu/almalinux/9.4/BaseOS/$basearch/os/
http://mirror.us.mirhosting.net/almalinux/9.4/BaseOS/$basearch/os/
http://mirror.facebook.net/almalinux/9.4/BaseOS/$basearch/os/
http://ash.mirrors.clouvider.net/almalinux/9.4/BaseOS/$basearch/os/⏎                                                                                                codyr@Portia ~/D/G/mirrors (mirrors_service)> curl https://mirrors.almalinux.org/mirrorlist/1.2345/baseos                                        2024-10-06 16:07:09
{"result":{"message":"Unknown version \"1.2345\". Allowed list of versions \"8, 8.10, 9, 9.4, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 8.7-beta, 8.8-beta, 8.9-beta, 8.10-beta, 9.0, 9.1, 9.2, 9.3, 9.1-beta, 9.2-beta, 9.3-beta, 9.4-beta\""},"status":"error","timestamp":1728245235}
```

Feel free to submit an issue :).

**Comment by brianjmurrell** [comment]
OK.  But the version matching logic issue was just an aside in this issue and not really that important (in regards to this issue).

Any idea why my private mirror is not being provided in the mirrorlist query?

**Comment by jonathanspw** [comment]
@brianjmurrell it seems to be a bug in the `private` logic somewhere.  The system is reporting no DNS record found for the domain - but that shouldn't be an issue when `private` is `true`.  I'm working on some other updates for the mirror system right now so I'll look into this as well as the funky version matching.

**Comment by jonathanspw** [comment]
@brianjmurrell public DNS needs to exist for the address - even if it goes nowhere.  There just needs to be an A record of some sort.  It can be a private IP, localhost, doesn't matter.

This is not so much a bug as it is an oversight...private mirrors have had this requirement since the inception of our mirrorlist service, though we should definitely fix and improve this.  We'll keep this issue open until we make said improvement.

**Comment by brianjmurrell** [comment]
@jonathanspw Roger that:

```
$ dig @ns1.he.net. pkgs.interlinx.bc.ca

; <<>> DiG 9.18.28 <<>> @ns1.he.net. pkgs.interlinx.bc.ca
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18289
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pkgs.interlinx.bc.ca.		IN	A

;; ANSWER SECTION:
pkgs.interlinx.bc.ca.	300	IN	A	127.0.0.1

;; Query time: 29 msec
;; SERVER: 2001:470:100::2#53(ns1.he.net.) (UDP)
;; WHEN: Mon Oct 07 11:42:42 EDT 2024
;; MSG SIZE  rcvd: 65
```

How long after the update of that record need does it take for the mirroring to get updated?

```
# curl -q -s 'https://mirrors.almalinux.org/mirrorlist/8.10/baseos' | grep interlinx
# 
```

**Comment by jonathanspw** [comment]
It takes about 15 minutes - and it looks like it is in the list now!
