### ISSUE TITLE
repo.almalinux.org is missing IPv6

### ISSUE THREAD

**Issue by liniuxs** [AlmaLinux/mirrors#1106]
Hello
We noticed that repo repo.almalinux.org is no more reachable trough IPv6, it seems it doesn't not have AAAA record anymore.
Is there a reason for that? We facing issues with ipv6 only hosts.
![image](https://github.com/user-attachments/assets/fa7a4cff-5086-44a7-bcec-3f909f98aeb9)

**Comment by jonathanspw** [comment]
Hey, sorry about that, it was not intentional.  This should be resolved now (might take a bit for DNS to propogate to your caching nameserver)

Side note: you should be using https://mirrors.almalinux.org for normal dnf/update traffic on your servers.
