### ISSUE TITLE
Regarding the ownership of Taiwan in your mirror list

### ISSUE THREAD

**Issue by Mohistman** [AlmaLinux/mirrors#126]
I found that you declared taiwan is a country in your mirror list site in this website: https://mirrors.almalinux.org/
我发现您在此网站 https://mirrors.almalinux.org/ 的镜像列表网站中宣称台湾是一个国家/地区。

However, Taiwan is not a country, but a part of the PRC (People's Republic of China).
然而，台湾并不是一个国家/地区，而是中华人民共和国的一部分。

Please correct the attribution of Taiwan in the mirror list. You can just write "China(Taiwan)". Thanks!
请您将镜像列表中台湾的归属进行修正。您可以直接写“中国（台湾）”。谢谢！

**Comment by jaboutboul** [comment]
Hello @Mohistman. Thanks for letting us know. Actually this is not something done ourselves. The library which parses location based on IP is what is used to generate the entries, so unfortunately this is not something in our control and cannot be changed at this time. You can file a request with the upstream library provider MaxMind (https://www.maxmind.com/) and see if they can help with this.

**Comment by 210hcl** [comment]
Maybe you cannot change "Taiwan" to "China(Taiwan)", but you can change "country" to "location", right?
Taiwan is not a country. Taiwan is a part of the PRC.

**Comment by andrewlukoshko** [comment]
We've changed Country to Location.
Thanks for proposing an easy way to resolve the issue.

**Comment by BraINstinct0** [comment]
Well that solves both technical and political problems at the same time!
