### ISSUE TITLE
403 on 'dnf check-update' from mirrorlist

### ISSUE THREAD

**Issue by evgkrsk** [AlmaLinux/mirrors#129]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/79869/116822550-a91ced00-aba9-11eb-95df-cbff0bfc8aad.png">

**Comment by andrewlukoshko** [comment]
Hello.
I can't reproduce it. Mirrorlist is available.

Please clear dnf cache completely and try again:
rm -fr /var/cache/dnf/*
dnf check-update

**Comment by evgkrsk** [comment]
HTTP code from server isn't depends on local dnf cache state, isn't it ?

However, removing cache is not working for me:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/79869/116851449-9099ea80-ac1c-11eb-9e20-c3ec970293ca.png">

Can you check mirrorlist's logs for this machine IP (79.141.65.125) ?

**Comment by evgkrsk** [comment]
It is interesting that I can't reproduce this problem from Virtualbox VM (also freshliy-installed from same AlmaLinux-8.3-x86_64-minimal.iso) on my home machine.

**Comment by mertcenikut** [comment]
https://mirror-denizli.cenuta.com/almalinux/timestamp.txt

Can you try again? @andrewlukoshko

**Comment by evgkrsk** [comment]
ping?

**Comment by andrewlukoshko** [comment]
Hi Evgenii.
I still can't reproduce it. I've tried from different locations and
`curl https://mirrors.almalinux.org/mirrorlist/8/baseos`
always returns mirrorlists.

Actually mirrorlists are hosted on GitHub pages https://github.com/AlmaLinux/mirrors/tree/gh-pages so we don't have access to web server logs to check what's going on with your requests.
Soon we'll move to self-hosted mirror infrastructure and if problem still occur we'll be able to check it.

Are you sure nothing in your infrastructure can block that access?

**Comment by evgkrsk** [comment]
Nope, seems like this case is sad consequence of NAT-ed network and tooo smart cloudflare security measures:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/79869/118405177-b86b6280-b6a0-11eb-8d8f-97b559ef6639.png">

(screenshot is tail of **curl -vs https://mirrors.almalinux.org/mirrorlist/8/baseos** output)


So at this moment the question is: how to use AlmaLinux from IP with poor reputation in third-party service (like CloudFlare)? Will such problems disappear when switching to self-hosted mirror infra will be completed?

**Comment by andrewlukoshko** [comment]
Well you can always set a desired mirror directly in `/etc/yum.repos.d/almalinux.repo`.
Use `baseurl` instead of `mirrorlist` for every repo.

For example, for Yandex mirror BaseOS section will look like that:
```
[baseos]
name=AlmaLinux $releasever - BaseOS
# mirrorlist=https://mirrors.almalinux.org/mirrorlist/$releasever/baseos
baseurl=http://mirror.yandex.ru/almalinux/8/BaseOS/$basearch/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
fastestmirror=1
```

**Comment by cloudlinuxadmin** [comment]
Maybe we should disable CloudFlare BIC check for those URLs?
https://support.cloudflare.com/hc/en-us/articles/200170086-Understanding-the-Cloudflare-Browser-Integrity-Check

**Comment by andrewlukoshko** [comment]
@cloudlinuxadmin
why not. let's try to do it for https://mirrors.almalinux.org/mirrorlist/* URLs.

**Comment by evgkrsk** [comment]
Thanks, work for me now.
