### ISSUE TITLE
Location wrong on almalinux.ourhome.kiwi

### ISSUE THREAD

**Issue by steriet** [AlmaLinux/mirrors#135]
Hello,

mirror 'almalinux.ourhome.kiwi' has location United-States, but it is located in New Zealand.
Please amend.

Thank you.

**Comment by andrewlukoshko** [comment]
Hello.
Looks like your mirror is behind Cloudflare that's why its location detected as US. And actually traffic goes from US as Cloudflare behaves like a proxy AFAIK.
Currently we can do nothing with that unfortunately as we fully rely on automatic detection for mirrors location.
