### ISSUE TITLE
Mirror mirror.ath1.fusioned.net is showing incorrect location

### ISSUE THREAD

**Issue by georgetasioulis** [AlmaLinux/mirrors#195]
Hello,

Our recently added mirror.ath1.fusioned.net mirror is located in Athens, Greece (can be verified through MaxMind), but it's showing as United Kingdom.
Can you please correct it? 

Thanks a lot!

<img width="1082" alt="Screenshot 2021-07-01 at 5 35 55 PM" src="https://user-images.githubusercontent.com/460954/124142513-f545ba00-da92-11eb-8a26-0848c18f9279.png">

**Comment by andrewlukoshko** [comment]
Hi! Thanks for report.
Fixed.
