### ISSUE TITLE
mirror.espoch.edu.ec and mirror.uta.edu.ec are not being shown

### ISSUE THREAD

**Issue by hc6pe** [AlmaLinux/mirrors#196]
timestamps for both are up to date.

**Comment by andrewlukoshko** [comment]
Hello.
The mirrors are updated but they are missing 8.4-beta version.
We automatically check for it too.

**Comment by andrewlukoshko** [comment]
We've removed 8.4-beta from our primary mirror and check so your mirrors are in list again.
Thanks.
