### ISSUE TITLE
removing old versions from the mirrors

### ISSUE THREAD

**Issue by hc6pe** [AlmaLinux/mirrors#197]
Other distros uses to remove the old version when a new one comes off. For example it 8.4/ is liberated, we suggest to empty 8.3/ 8.3-rc/ 8.3-beta/ and so on.
Our mirrors are growing too fast by keeping old versions present in the mirrors. I suggest to create, for example, a vault.almalinux.org in order to store old versions and not hit the mirrors HD usage too hard.

**Comment by andrewlukoshko** [comment]
Hello.
We've already moved 8.3-beta and 8.3-rc to https://repo.almalinux.org/vault/ dir which is not mirrored.
Soon we'll move 8.3 stable too.
Thanks.

**Comment by soksanichenko** [comment]
Old versions were removed.
