### ISSUE TITLE
mirror.mijn.host issues resolved, re-add mirror

### ISSUE THREAD

**Issue by egogo-nl** [AlmaLinux/mirrors#210]
Hello,
Our mirror ([https://mirror.mijn.host](https://mirror.mijn.host)) was down because of infrastructure change.
Now the mirror is working again, and will stay working.
Can you re-add our mirror? The mirror file is already in the mirrors.d directory (9ec6628).

**Comment by andrewlukoshko** [comment]
Hello! Sure!
Welcome back! https://mirrors.almalinux.org
