### ISSUE TITLE
mirrors.almalinux.org resolve problem

### ISSUE THREAD

**Issue by aleks-o** [AlmaLinux/mirrors#219]
Hello,
mirrors.almalinux.org is not resolving right now. Is it OK?

![image](https://user-images.githubusercontent.com/19662235/128170134-140109f3-34f3-4bfc-b6cc-3f2a0b90427d.png)

**Comment by discostur** [comment]
@aleks-o looks like a duplicate: https://github.com/AlmaLinux/mirrors/issues/218

**Comment by andrewlukoshko** [comment]
Sorry for that. We’re switching to new mirror service right now
https://www.reddit.com/r/AlmaLinux/comments/oxnno4/new_almalinux_mirror_service/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by zstack25** [comment]
same shit agen? not resolving to mirror of almalinux9

**Comment by codyro** [comment]
> same shit agen? not resolving to mirror of almalinux9

There are no known issues related to mirror.almalinux.org or the mirror service. Is it a specific mirror you're having issues with?
