### ISSUE TITLE
Azure mirror listed on downloads page is down

### ISSUE THREAD

**Issue by vwbusguy** [AlmaLinux/mirrors#224]
At least one of the Azure mirrors listed on the downloads page is currently down (for both x86_64 and aarch64): http://eastus.azure.repo.almalinux.org/almalinux/8.4/isos/x86_64

**Comment by johanburati** [comment]
> At least one of the Azure mirrors listed on the downloads page is currently down (for both x86_64 and aarch64): http://eastus.azure.repo.almalinux.org/almalinux/8.4/isos/x86_64

Looks like the **isos** folder your refer to is missing from the Azure mirrors:
```
$ links -dump http://eastus.azure.repo.almalinux.org/almalinux/8.4/
                            Index of /almalinux/8.4/

     ----------------------------------------------------------------------

 ../
 AppStream/                                         25-Jun-2021 09:28                   -
 BaseOS/                                            25-Jun-2021 09:28                   -
 HighAvailability/                                  25-Jun-2021 09:28                   -
 PowerTools/                                        25-Jun-2021 09:28                   -
 devel/                                             25-Jun-2021 09:34                   -
 extras/                                            25-Jun-2021 09:28                   -
 live/                                              02-Aug-2021 10:58                   -
 metadata/                                          26-May-2021 07:37                   -

     ----------------------------------------------------------------------
```

**Comment by vwbusguy** [comment]
@johanburati The link I gave was the link presented from the Alma [download page](https://mirrors.almalinux.org/isos/x86_64/8.4.html).

![image](https://user-images.githubusercontent.com/5474941/130160270-3b73c95e-2cfa-482f-a08b-8556ce221edb.png)
![image](https://user-images.githubusercontent.com/5474941/130160299-fff37372-0ab0-45ee-b313-65cd7a7c0828.png)

**Comment by andrewlukoshko** [comment]
@vwbusguy nice catch!
Thanks, we're looking into it

**Comment by soksanichenko** [comment]
The Azure mirrors are excluded from the list on ISOs page.
