### ISSUE TITLE
Explicitly ignore specific mirrors

### ISSUE THREAD

**Issue by b3taman** [AlmaLinux/mirrors#235]
[Maybe I could use better search terms, but I was unable to find an answer to this, which became a problem with the automatic geo-based mirror choice.]

Unfortunately my closest fast mirror does not support HTTPS and so I'd prefer not to use it. As a result updates frequently come up with things like this: `
[MIRROR] kernel-4.18.0-305.12.1.el8_4.x86_64.rpm: Curl error (7): Couldn't connect to server for https://almalinux-mirror.datakeepers.co.za/8/BaseOS/x86_64/os/Packages/kernel-4.18.0-305.12.1.el8_4.x86_64.rpm [Failed to connect to almalinux-mirror.datakeepers.co.za port 443: Connection refused]`

How can I only resolve HTTPS-capable sites or is there a way to set up blacklists?

Both would have their uses but in this case the former would be best.

**Comment by andrewlukoshko** [comment]
Hello.
DNF doesn't allow to exclude particular mirror or protocol but you can just setup desired mirror in baseurl= and comment mirrorlist= in /etc/yum.repos.d/*.repo.
Is it suitable?

**Comment by b3taman** [comment]
Thank you for the reply. I'll look into it a bit.

The point is that I still want the geo-based algorithm to find the fastest mirror, but to ignore mirrors in a blacklist (for whatever reason: http-only, suspect, etc.)

Is that possible?

**Comment by andrewlukoshko** [comment]
I'm afraid dnf doesn't allow to filter specific mirrors from mirrorlist.
You can open an issue with feature request in libdnf upstream project https://github.com/rpm-software-management/libdnf
