### ISSUE TITLE
Mirror service over IPv6 returns full list of mirrors

### ISSUE THREAD

**Issue by karelvanhecke** [AlmaLinux/mirrors#245]
When I request the mirror list over IPv4, the mirror service works as expected and returns a total of 9 mirrors.
Over IPv6 the service always returns the full list.

Both my IPv4 and IPv6 address are resolved to the correct country when tested with the [Maxmind demo](https://www.maxmind.com/en/geoip-demo/).

The service should be able to detect the correct country based on my IPv6 address utilizing the Maxmind database, so something else is causing the mirror service to fall back to returning the complete list.

**Comment by soksanichenko** [comment]
Hello.
Thank you for the report.

Please, can you provide some details, because I can't reproduce the issue with my IPv6?
1. URL which returns full list of the mirrors
2. Your IPv6 (you can write it to PM)
Thank you

**Comment by karelvanhecke** [comment]
https://mirrors.almalinux.org/mirrorlist/8.4/baseos
https://mirrors.almalinux.org/isos/x86_64/8.4.html

Can be reproduced with both URL's

**Comment by soksanichenko** [comment]
Thank you!
I will investigate this issue.

**Comment by soksanichenko** [comment]
@karelvanhecke Hello.
We released new version of the service.
Please, can you check the mirror list for ipv6 connection?
Thank you

**Comment by karelvanhecke** [comment]
> 
> 
> @karelvanhecke Hello.
> We released new version of the service.
> Please, can you check the mirror list for ipv6 connection?
> Thank you

Correct list of mirrors is now returned by the service for my IPv6 connection.
