### ISSUE TITLE
Certificates for fusioned.net mirrors expired

### ISSUE THREAD

**Issue by rafasc** [AlmaLinux/mirrors#249]
This seems to affect both the Netherlands https://mirror.nl.fusioned.net and Greece https://mirror.ath1.fusioned.net mirrors.

cc: @alex1x
cc: @georgetasioulis

**Comment by georgetasioulis** [comment]
Sorry about that, this has been fixed now.

**Comment by rafasc** [comment]
No worries, thanks for the quick fix.
