### ISSUE TITLE
Continent not shoiw in https://mirrors.almalinux.org/

### ISSUE THREAD

**Issue by sysdev-isu** [AlmaLinux/mirrors#341]
Dears

The location is fine in maxmind GeoIP it shows the continent Asia but not reflected into https://mirrors.almalinux.org/

<h3>
    GeoIP2 
    <span class="js-geoip-result-type-name">City</span>
    Results
  </h3>

<div id="result-table" class="sticky-table__wrapper" style="">
  <div class="sticky-table__scroller result-table__table">
    

IP Address | Country Code | Location | Network | Postal Code | Approximate Coordinates* | Accuracy Radius (km) | ISP | Organization | Domain | Metro Code
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
212.138.72.17 | SA | Riyadh,Riyadh Region,Saudi Arabia,Asia | 212.138.64.0/20 |   | 24.6569,46.7179 | 5 | King Abdul Aziz City for Science and Technology | King Abdul Aziz City for Science and Technology

</div></div>

Regards

**Comment by jonathanspw** [comment]
It's likely that the geoip data hasn't made it down to the free GeoIP database yet.  It should fix itself in the future.
