### ISSUE TITLE
Private mirror IPs are checked.

### ISSUE THREAD

**Issue by jonathanspw** [AlmaLinux/mirrors#418]
We need to avoid checking if there is valid DNS for private mirrors.  It's to be assume they may be using local DNS.

Context: https://chat.almalinux.org/almalinux/pl/qqhae7u3zffgdy4y7i9ubjdgye

**Comment by brianjmurrell** [comment]
Any progress/ETA on this?

**Comment by soksanichenko** [comment]
@brianjmurrell Looks like it works. I tried to get mirrorlist using the IP from the mirror's subnets:

```
[soksanichenko@localhost ~]$ curl -H "X-Forwarded-For: 69.165.217.196" https://mirrors.almalinux.org/mirrorlist/8/baseos
http://pkgs.interlinx.bc.ca:3142/almalinux/8/BaseOS/$basearch/os/
http://mirror.csclub.uwaterloo.ca/almalinux/8/BaseOS/$basearch/os/
http://mirror.12z.eu/pub/linux/almalinux/8/BaseOS/$basearch/os/
http://mirror.myaccess.ca/8/BaseOS/$basearch/os/
http://dist-mirror.fibernetics.ca/almalinux/8/BaseOS/$basearch/os/[soksanichenko@localhost ~]$
```

**Comment by brianjmurrell** [comment]
Interesting.  I can reproduce your results.  But how is `X-Forwarded-For: $my_ip_address` supposed to get added to the HTTP requests going to https://mirrors.almalinux.org/mirrorlist/`?

**Comment by soksanichenko** [comment]
It's not mandatory. The service gets an IP of client using that header or a request's IP. And I can emulate needed IP for checking right work of the service using that header.
The IP can be added automatically into that header when going through some proxy or something like this.
Just check your real IP if you got wrong answer from the service.

**Comment by brianjmurrell** [comment]
> The IP can be added automatically into that header when going through some proxy or something like this.

Are you inferring that it's up to my infrastructure to add that header to all outgoing requests in order for private mirrors to work?  If so, that is a non-starter and I refer back to my suggestion of using mirror-manager which does not require network admins do anything special with their networks in order for private mirrors to work.

Adding that header, honestly, sounds like it's the job of the mirroring infrastructure.  Probably the load balancer perhaps.

> Just check your real IP if you got wrong answer from the service.

I still get the wrong answer (without adding the "X-Forwarded-For: ..." header) and I have verified that I am using an IP that works when I explicitly add it to a `curl -H "X-Forwarded-For: ..."` fetch.

**Comment by soksanichenko** [comment]
I guess that header could exist, but it's not mandatory. And I use a request's IP if the header is absent.
Can you write me your IP? I'll check the logs of backend.

**Comment by brianjmurrell** [comment]
135.23.51.187

**Comment by soksanichenko** [comment]
Hmm, I didn't find any suspicious.
Can you write me result of viewing http://54.89.99.176/my_ip_and_headers (it's my dev machine in AWS with deployed the mirrors service) and write me traceroute to mirrors.almalinux.org.
Thank you.

**Comment by brianjmurrell** [comment]
```
{
Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
Accept-Encoding: "gzip, deflate",
Accept-Language: "en-US,en;q=0.9,en-AU;q=0.8,en-CA;q=0.7,en-NZ;q=0.6,en-GB;q=0.5,en-ZA;q=0.4",
Connection: "close",
Dnt: "1",
Host: "54.89.99.176",
Upgrade-Insecure-Requests: "1",
User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
X-Forwarded-For: "135.23.51.187",
X-Real-Ip: "135.23.51.187",
my_ip: "::1"
}
```

**Comment by brianjmurrell** [comment]
Was that test result helpful?

**Comment by soksanichenko** [comment]
Sorry, but I'm far away from work PC and will continue checks on Monday.
But you can make the traceroute to mirrors.almalinux.org, call http://54.89.99.176/mirrorlist/8/baseos and show me the result.
It will be very helpful for searching of root of the issue.
Thank you.

**Comment by brianjmurrell** [comment]
traceroute:

```
[my local network and ISP networks]
 7  52.93.3.90 (52.93.3.90)  38.314 ms
 8  52.93.3.104 (52.93.3.104)  28.181 ms
 9  *
10  *
11  *
12  *
13  *
14  *
15  *
16  *
17  *
18  *
19  *
20  *
21  *
22  *
23  *
24  *
25  *
26  *
27  *
28  *
29  *
30  *
```
mirrors.almalinux.org seems to have the traceroute ports blocked, hence all of hte `*` hops at the end.

http://54.89.99.176/mirrorlist/8/baseos:
```
http://pkgs.interlinx.bc.ca:3142/almalinux/8/BaseOS/$basearch/os/
http://mirror.12z.eu/pub/linux/almalinux/8/BaseOS/$basearch/os/
http://mirror.csclub.uwaterloo.ca/almalinux/8/BaseOS/$basearch/os/
http://mirror.myaccess.ca/8/BaseOS/$basearch/os/
http://dist-mirror.fibernetics.ca/almalinux/8/BaseOS/$basearch/os/
```

Which looks good, but is not what https://mirrors.almalinux.org/mirrorlist/8/baseos returns:

```
http://mirror.csclub.uwaterloo.ca/almalinux/8/BaseOS/$basearch/os/
http://mirror.12z.eu/pub/linux/almalinux/8/BaseOS/$basearch/os/
http://mirror.myaccess.ca/8/BaseOS/$basearch/os/
http://dist-mirror.fibernetics.ca/almalinux/8/BaseOS/$basearch/os/
http://mirror.its.dal.ca/almalinux/8/BaseOS/$basearch/os/
http://mirror.esecuredata.com/almalinux/8/BaseOS/$basearch/os/
http://mirror.siena.edu/almalinux/8/BaseOS/$basearch/os/
http://iad.mirror.rackspace.com/almalinux/8/BaseOS/$basearch/os/
http://nc-mirror.iwebfusion.net/almalinux/8/BaseOS/$basearch/os/
http://mirror.nyc.velocihost.net/almalinux/8/BaseOS/$basearch/os/
```

**Comment by soksanichenko** [comment]
It's interesting. Looks like AWS Load Balancer did something that overrides right value of header `X-Forwarded-For`. I'll deploy debug endpoint `/my_ip_and_headers` on Monday and we will continue checks on prod.

**Comment by soksanichenko** [comment]
@brianjmurrell hi.
Are you sure that the first external IP in `[my local network and ISP networks]` (look at your traceroute) is `135.23.51.187`.
Also we cache all mirrorlists per IP in redis (for better performance of the service) and I didn't find your IP in that list. It means that the service caches mirrorlist for you under another IP 🤔 therefore the service calculates mirrorlist for another IP.

```
[ec2-user@ip-172-30-60-107 ~]$ redis-cli
127.0.0.1:6379> keys "135.23.51.187"
(empty list or set)
127.0.0.1:6379>
[ec2-user@ip-172-30-60-107 ~]$ logout
[soksanichenko@soksanichenko ~]$ ssh ec2-user@54.237.243.82
Last login: Mon Jan 24 10:35:20 2022 from 77.121.201.30
[ec2-user@ip-172-30-92-162 ~]$ redis-cli
127.0.0.1:6379> keys "135.23.51.187"
(empty list or set)
127.0.0.1:6379>
[ec2-user@ip-172-30-92-162 ~]$
```

I deployed the debug endpoint `/my_ip_and_headers` to production: https://mirrors.almalinux.org/my_ip_and_headers. Please, call it and send me the result.
Thank you.

**Comment by brianjmurrell** [comment]
```
{
result: {
Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
Accept-Encoding: "gzip, deflate, br",
Accept-Language: "en-US,en;q=0.9,en-AU;q=0.8,en-CA;q=0.7,en-NZ;q=0.6,en-GB;q=0.5,en-ZA;q=0.4",
Connection: "close",
Cookie: "rl_page_init_referrer=RudderEncrypt%3AU2FsdGVkX1%2BQCPkPkYmPlwTmq%2BnxnObGuapp5MDzmtU%3D; rl_page_init_referring_domain=RudderEncrypt%3AU2FsdGVkX19srlSGxAjuZ%2BX5gIW53RVI%2FlE7uiRJPbw%3D; rl_anonymous_id=RudderEncrypt%3AU2FsdGVkX1%2B7enY8mUU74jyLNXrn3SmZnT%2FzBtiwLlJYDK%2BgAOMRhSdROQuX4KCPuYOgwDu9UJRN4Z57Htx6lw%3D%3D; rl_group_id=RudderEncrypt%3AU2FsdGVkX19irxSLmAozuay%2BmLSz2e6GaJ3YRnQNnJU%3D; rl_group_trait=RudderEncrypt%3AU2FsdGVkX18xFknlT60Cqdl8binTJlLkcWfl9Gd9%2Ba4%3D; rl_user_id=RudderEncrypt%3AU2FsdGVkX19aUDQGrLvGKADCj04fxYFKreD1jSnvMhputA6zI5zrc%2BeBjJSIaITO; rl_trait=RudderEncrypt%3AU2FsdGVkX1%2FL4BaiXOgUSuJvVLPbjIjtRNgdCuTPd20%3D",
Dnt: "1",
Host: "mirrors.almalinux.org",
Referer: "https://github.com/AlmaLinux/mirrors/issues/418",
Sec-Ch-Ua: "" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"",
Sec-Ch-Ua-Mobile: "?0",
Sec-Ch-Ua-Platform: ""Linux"",
Sec-Fetch-Dest: "document",
Sec-Fetch-Mode: "navigate",
Sec-Fetch-Site: "cross-site",
Sec-Fetch-User: "?1",
Upgrade-Insecure-Requests: "1",
User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
X-Amzn-Trace-Id: "Root=1-61eed0eb-2709f78b0194bcb01851d5d9",
X-Forwarded-For: "2001:470:b038:0:90cc:a629:cf42:5877, 172.30.28.80",
X-Forwarded-Port: "443",
X-Forwarded-Proto: "https",
X-Real-Ip: "172.30.28.80",
my_ip: "::1"
},
status: "ok",
timestamp: 1643041003
}
```

172.30.28.80 is of course unrouted RFC1918 space.  Looks like AWS is doing some kind of NAT behind your backs perhaps.

**Comment by soksanichenko** [comment]
We use first IP from the header. I see IPv6 address `2001:470:b038:0:90cc:a629:cf42:5877`. 
I'll check it in the cache.
And `172.30.28.80` is address of the Load Balancer.

**Comment by soksanichenko** [comment]
Hmm, looks like your IPv6 address `2001:470:b038:0:90cc:a629:cf42:5877` doesn't belong to subnet `2001:470:1c:6f8::/64` from the mirror's config
@brianjmurrell

**Comment by brianjmurrell** [comment]
Oh damn!  That's the old subnet.  Let me update the mirror entry.  Sorry for the wild goose chase.

**Comment by soksanichenko** [comment]
I merged the PR, but found some related issue. I'm investing it. I will notify you if there are any updates.

**Comment by soksanichenko** [comment]
@brianjmurrell 
I updated the mirrors list on the prod and flush the cache and the service returns right list

```
[soksanichenko@soksanichenko ~]$ curl -H "X-Forwarded-For: 2001:470:b038:0:90cc:a629:cf42:5877" https://mirrors.almalinux.org/mirrorlist/8/baseos
http://pkgs.interlinx.bc.ca:3142/almalinux/8/BaseOS/$basearch/os/
http://mirror.csclub.uwaterloo.ca/almalinux/8/BaseOS/$basearch/os/
http://mirror.12z.eu/pub/linux/almalinux/8/BaseOS/$basearch/os/
http://mirror.myaccess.ca/8/BaseOS/$basearch/os/
http://dist-mirror.fibernetics.ca/almalinux/8/BaseOS/$basearch/os/[soksanichenko@soksanichenko ~]$
```
Please, check it on your side.
Thank you.
