### ISSUE TITLE
Only return private mirrors

### ISSUE THREAD

**Issue by brianjmurrell** [AlmaLinux/mirrors#425]
When using private mirrors, I really only want the mirrorlist query to return my private mirrors.

It could very well be that my machines can only reach my mirrors.

Even if my machines can reach public mirrors, if my mirrors are broken, I want dnf to break and tell me that the mirror is broken rather than doing an end-run around it and using public mirrors.

Perhaps this functionality should be optional/selectable.

**Comment by soksanichenko** [comment]
@brianjmurrell Hi.
It's finally implemented and deployed to production and it works fine:

```
[soksanichenko@localhost ~]$ curl -H "X-Forwarded-For: 69.165.217.196" https://mirrors.almalinux.org/mirrorlist/8/baseos
http://pkgs.interlinx.bc.ca:3142/almalinux/8/BaseOS/$basearch/os/[soksanichenko@localhost ~]$
```

I added parameter `monopoly` to a private mirror config (see more info on [wiki](https://wiki.almalinux.org/Mirrors.html)) and edited config of your mirror.

**Comment by brianjmurrell** [comment]
Yes, that seems to be working great now.

Thanks!
