### ISSUE TITLE
Add route to fetch closest ISO URL

### ISSUE THREAD

**Issue by jonathanspw** [AlmaLinux/mirrors#447]
Something similar to `/mirrorlist` but that will only return the base URL of the closest mirror.  Perhaps we could simply add a route for `/mirrorlist/<version>` to serve this list of base URLs.

This would allow a quality of life improvement in https://github.com/AlmaLinux/cloud-images so that it can fetch ISOs from a better mirror than the currently hard-coded `repo.almalinux.org`.

This can probably be used in other automated processes and projects as well.

**Comment by soksanichenko** [comment]
It's already on the production
https://mirrors.almalinux.org/isolist/8/x86_64

**Comment by jonathanspw** [comment]
That URL 404s.

**Comment by soksanichenko** [comment]
It's fixed.
@jonathanspw  please, check again.
Thank you!

**Comment by srbala** [comment]
@jonathanspw Please verify and close

**Comment by jonathanspw** [comment]
Looks good.
