### ISSUE TITLE
Unable to download older versions of Almalinux

### ISSUE THREAD

**Issue by jamie-dit** [AlmaLinux/mirrors#568]
I've noticed that older versions of Almalinux are no longer available from all mirrors. This causes issues with tools such as Netboot and prevents installations from using these versions.

These versions should at least be available for 12-24 months.

**Comment by jonathanspw** [comment]
Old versions are moved to the vault pretty soon after new versions are released.

If you need to use static versions for things like netboot you can either use vault mirrors or run a local mirror.
