### ISSUE TITLE
mirror.mijn.host IP change

### ISSUE THREAD

**Issue by egogo-nl** [AlmaLinux/mirrors#586]
Because of a server migration, our IPs will change for mirror.mijn.host.

178.162.180.129
2001:1af8:8100:a005:5::2

Currently we cannot rsync from this IPs. Can you add these IPs please?

**Comment by jonathanspw** [comment]
We don't lock the rsync mirror by IP so you should have no problems accessing it.

Can you check traceroute and MTR for any issues?
