### ISSUE TITLE
Add the ability to filter mirrorlist by protocol type (ie only get HTTPS mirrors).

### ISSUE THREAD

**Issue by ladar** [AlmaLinux/mirrors#590]
I've been all over the code, and I can't find a route inside mirror listing code (on the [mirrors_service](https://github.com/AlmaLinux/mirrors/tree/23567b34ffa8b040555a6e64c54c4ce10afcb5df/) branch) that will let me filter the results by protocol. 

I would like to update the DNF repo config mirrorlist URL so it only retrieves and uses HTTPS capable mirrors.

With the Fedora mirror service, it's possible to filter the results by appending `&protocol=https` to the mirrorlist URL. For example, to get a list of HTTPS mirrors for the [EPEL](https://mirrors.fedoraproject.org/metalink?repo=epel-9&arch=x86_64&protocol=https) repo, you could use:

```
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir&protocol=https
```
Or to get a list HTTPS mirrors for the [Fedora 36](https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64&protocol=https) repo:

```
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch&protocol=https
```

**Comment by jonathanspw** [comment]
This is a great suggestion.  @soksanichenko let's make this happen :)

**Comment by soksanichenko** [comment]
I agree, it's great suggestion. I will implement it as soon as I will free from another AL related urgent tasks. I'm sorry :(

**Comment by ladar** [comment]
Ticklme me Elmo. Or should I say @soksanichenko ... are you still swamped?

**Comment by soksanichenko** [comment]
Yep, sorry I'm still swamped.

**Comment by jonathanspw** [comment]
There was a request in Mattermost last night to support something like "?country=US" or similar.  Perhaps it should be part of this as well to support requesting mirrors in a specific country based on 2-letter country codes.

**Comment by faitjx** [comment]
This is becoming an urgent issue for groups working on any of the DOE managed labs scattered about the US, and for any other entities that are mandating a HTTPS only environment via draconian firewall policies.  I have had to bypass the mirrorlists entirely, as sending out a request via HTTP will get all traffic from that IP address blocked for several hours for each request.  Being able to specify the protocol in some way would be priceless for me and others working at the lab, and perhaps should become the default, as every mirror that I have queried directly has supported HTTPS access.  Alternatively, have HTTPS as the default, and HTTP as the fallback protocol is a more reasonable approach for sites in today's environment.

**Comment by jonathanspw** [comment]
> This is becoming an urgent issue for groups working on any of the DOE managed labs scattered about the US, and for any other entities that are mandating a HTTPS only environment via draconian firewall policies. I have had to bypass the mirrorlists entirely, as sending out a request via HTTP will get all traffic from that IP address blocked for several hours for each request. Being able to specify the protocol in some way would be priceless for me and others working at the lab, and perhaps should become the default, as every mirror that I have queried directly has supported HTTPS access. Alternatively, have HTTPS as the default, and HTTP as the fallback protocol is a more reasonable approach for sites in today's environment.

Thanks for that context.  I'll prioritize this issue!

**Comment by jonathanspw** [comment]
This enhancement is in production:

```
$ curl https://mirrors.almalinux.org/mirrorlist/9/baseos
http://bna.aws.repo.almalinux.org/9.4/BaseOS/$basearch/os/
http://www.gtlib.gatech.edu/pub/almalinux/9.4/BaseOS/$basearch/os/
http://atl.mirrors.clouvider.net/almalinux/9.4/BaseOS/$basearch/os/
http://paducahix.mm.fcix.net/almalinux/9.4/BaseOS/$basearch/os/
http://atl.mirrors.knownhost.com/almalinux/9.4/BaseOS/$basearch/os/
http://nc-mirror.iwebfusion.net/almalinux/9.4/BaseOS/$basearch/os/
http://mirror.nodesdirect.com/almalinux/9.4/BaseOS/$basearch/os/
http://almalinux.stl.us.ssimn.org/9.4/BaseOS/$basearch/os/
http://mirror.vtti.vt.edu/almalinux/9.4/BaseOS/$basearch/os/
http://mirror.linux.duke.edu/almalinux/9.4/BaseOS/$basearch/os/

$ curl https://mirrors.almalinux.org/mirrorlist/9/baseos?protocol=https
https://bna.aws.repo.almalinux.org/9.4/BaseOS/$basearch/os/
https://paducahix.mm.fcix.net/almalinux/9.4/BaseOS/$basearch/os/
https://atl.mirrors.clouvider.net/almalinux/9.4/BaseOS/$basearch/os/
https://atl.mirrors.knownhost.com/almalinux/9.4/BaseOS/$basearch/os/
https://nc-mirror.iwebfusion.net/almalinux/9.4/BaseOS/$basearch/os/
https://mirror.nodesdirect.com/almalinux/9.4/BaseOS/$basearch/os/
https://almalinux.stl.us.ssimn.org/9.4/BaseOS/$basearch/os/
https://mirror.vtti.vt.edu/almalinux/9.4/BaseOS/$basearch/os/
https://mirror.linux.duke.edu/almalinux/9.4/BaseOS/$basearch/os/
https://almalinux-mirror.tpa.hivelocity.net/9.4/BaseOS/$basearch/os/
```

The `country` flag also has an initial implementation but it does not work with the `protocol` flag currently.

```
$ curl -s https://mirrors.almalinux.org/mirrorlist/9/baseos?country=UK
http://mirror.ox.ac.uk/sites/repo.almalinux.org/9.4/BaseOS/$basearch/os/
http://almalinux.linuxpatch.com/9.4/BaseOS/$basearch/os/
```
