### ISSUE TITLE
mirror.hnd.cl fixed 

### ISSUE THREAD

**Issue by ralvaradof** [AlmaLinux/mirrors#651]
Hi,

Our mirror has been fixed after a disk capacity problem, please can you re-add it? The mirror file its already on mirrors.d https://github.com/AlmaLinux/mirrors/pull/614

Sorry for the problem,  our internal monitoring system has been reconfigured to avoid this problems in the future.

Thanks
Regards

**Comment by jonathanspw** [comment]
It should reappear automatically.  I'll leave this open to verify it's there.

**Comment by ralvaradof** [comment]
If I check  https://mirrors.almalinux.org/ the site randomly shows 207, 219 or 221 active mirrors, our mirror only get listed when 207 mirrors are shown.

**Comment by ralvaradof** [comment]
still without comeback :( 

how I can check why??

**Comment by ralvaradof** [comment]
The problem was an ipv6 routing issue, this is fixed now and the mirror is listed, issue resolved.
