### ISSUE TITLE
The mirror.upr.edu #701 still missing from the list https://mirrors.almalinux.org

### ISSUE THREAD

**Issue by soksanichenko** [AlmaLinux/mirrors#708]

**Comment by soksanichenko** [comment]
I checked the issue with your mirror.
Looks like you have the similar problem as in https://github.com/AlmaLinux/mirrors/issues/688
Your mirror is not available through IPv6 from our service. I try `curl --ipv6 -v mirrors.upr.edu` from my dev machine in AWS and get timeout error.

**Comment by limdahost** [comment]
@soksanichenko  Getting the same issue with mirror.limda.net

It was available earlier without any issue but seems not anymore available after enabling IPV6 on the network. 
I have checked but everything seems fine from my end.

**Comment by limdahost** [comment]
I can see mine is available now. Perhaps it was an issue with DNS propagation. 

Thank you so much @soksanichenko for the quick response.  <3
