### ISSUE TITLE
Wrong Country for mirror.alwyzon.net shown

### ISSUE THREAD

**Issue by hohl** [AlmaLinux/mirrors#85]
The country on <https://mirrors.almalinux.org/> for [mirror.alwyzon.net](https://mirror.alwyzon.net) incorrectly shows Romania instead of Austria. I guess this is based on a GeoIP database? Any chance the used database copy needs an update? The IPs were used by an Romanian ISPs a while ago, but the [RIPE database entries](https://apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=46.102.157.40%20-%2046.102.157.47&type=inetnum) and all major GeoIP databases (MaxMind, ipinfo.io, ...) should all correctly show Austria.

**Comment by georgetasioulis** [comment]
Same for mirror.nl.fusioned.net which is located in the Netherlands, not in the UK.

**Comment by hohl** [comment]
Very likely, one would only need to re-download the `geoip_db.mmdb` in the root of this repository which seems to be a GeoLite2 database from MaxMind.

**Comment by andrewlukoshko** [comment]
Thanks we're looking into it

**Comment by soksanichenko** [comment]
Hello @georgetasioulis and @hohl.
We updated the geoip db and yours mirrors have right country: https://mirrors.almalinux.org/.
Thanks you.
