### ISSUE TITLE
IPs without specific geolocation disproportionately hit some mirrors

### ISSUE THREAD

**Issue by jonathanspw** [AlmaLinux/mirrors#871]
Source IPs (and mirror IPs) without IP geolocation more specific than "United States, North America" which translates to coordinates "37.751, -97.822" are disproportionately hit with traffic.  This likely impacts generic geolocation points in other countries/continents as well.

We should probably add a degree of greater randomization for requests from such IPs because we truly have no idea where they are within a given country.

**Comment by codyro** [comment]
I've contacted `ipinfo.io` to see if we can access their offline database, as it appears to be much more accurate than what we use.

While this wouldn't fully resolve this issue, it helps improve the QoL of the mirror service as a whole/help this issue.

**Comment by jonathanspw** [comment]
Fixed by #881
